'use client'

import React, { useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { AcvaReviewEditor } from '@/components/acva-review-editor'
import { ArrowLeft, CheckCircle2, AlertTriangle, Loader2 } from 'lucide-react'

// Mock submission data
const mockSubmissions: Record<string, any> = {
  'SUB-001': {
    id: 'SUB-001',
    entityId: 'ENT-001',
    entityName: 'Cement Manufacturing Ltd',
    period: 'Q1 FY2024-25',
    uploadedAt: new Date('2024-01-15'),
    status: 'pending-verification',
    activityData: [
      { fuelType: 'Coal', quantity: 4500, unit: 'tonnes', consumption: 4200 },
      { fuelType: 'Natural Gas', quantity: 1200, unit: 'MWh', consumption: 1150 },
      { fuelType: 'Biomass', quantity: 800, unit: 'tonnes', consumption: 750 },
    ],
    productionData: {
      cement: 15000, // tonnes
      clinker: 9500,
    },
    calculatedMetrics: {
      gei: 0.58,
      carbonCredits: 14850,
      dataQuality: 87,
    },
  },
}

// Mock auto-generated comments
const mockAutoGeneratedComments = [
  {
    id: 'comment-1',
    commentType: 'CRITICAL',
    severity: 'critical',
    commentText: 'Missing quality assurance records for fuel sampling in Q1. Per CCTS guidelines, quarterly fuel samples must have lab analysis reports.',
    relatedField: 'Fuel Consumption Data',
    isAutoGenerated: true,
    modifiedByReviewer: false,
  },
  {
    id: 'comment-2',
    commentType: 'MAJOR',
    severity: 'major',
    commentText: 'Electricity meter calibration certificate expired in November 2023. Updated calibration required before data validation.',
    relatedField: 'Natural Gas Consumption',
    isAutoGenerated: true,
    modifiedByReviewer: false,
  },
  {
    id: 'comment-3',
    commentType: 'MAJOR',
    severity: 'major',
    commentText: 'Production data shows 15% variation from 3-year average. Please provide explanation and supporting documents for Q1 spike.',
    relatedField: 'Production Data',
    isAutoGenerated: true,
    modifiedByReviewer: false,
  },
  {
    id: 'comment-4',
    commentType: 'MINOR',
    severity: 'minor',
    commentText: 'GEI calculation uses previous year emission factors. Recommend updating to latest BEE sector baselines for improved accuracy.',
    relatedField: 'GEI Calculation',
    isAutoGenerated: true,
    modifiedByReviewer: false,
  },
]

export default function SubmissionReviewPage() {
  const params = useParams()
  const submissionId = params.id as string
  const submission = mockSubmissions[submissionId]
  const [showEditor, setShowEditor] = useState(false)
  const [isSending, setIsSending] = useState(false)
  const [reviewSent, setReviewSent] = useState(false)

  if (!submission) {
    return (
      <div className="min-h-screen bg-background p-6">
        <Button asChild variant="outline" className="gap-2 mb-6">
          <Link href="/submissions">
            <ArrowLeft className="w-4 h-4" />
            Back to Submissions
          </Link>
        </Button>
        <Card className="border-destructive/50">
          <CardContent className="pt-6">
            <p className="text-destructive">Submission not found</p>
          </CardContent>
        </Card>
      </div>
    )
  }

  const handleSendReview = async (comments: any[], dueDate: Date) => {
    setIsSending(true)
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 1500))
    setIsSending(false)
    setReviewSent(true)
    setShowEditor(false)
    
    // Reset after 3 seconds
    setTimeout(() => setReviewSent(false), 3000)
  }

  return (
    <div className="min-h-screen bg-background p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <Button asChild variant="outline" size="sm">
              <Link href="/submissions">
                <ArrowLeft className="w-4 h-4" />
              </Link>
            </Button>
            <h1 className="text-3xl font-bold text-foreground">Submission Review</h1>
          </div>
          <p className="text-muted-foreground">ACVA Verification and Comment Management</p>
        </div>
      </div>

      {/* Success Alert */}
      {reviewSent && (
        <Alert className="border-emerald-500/30 bg-emerald-900/20">
          <CheckCircle2 className="w-4 h-4 text-emerald-400" />
          <AlertDescription className="text-emerald-300">
            Review comments sent successfully to {submission.entityName} via DMRV Portal (dmrv.bee.gov.in). Entity can view feedback at: <span className="font-semibold">dmrv.bee.gov.in/submissions/{submissionId}/feedback</span>. Submission status updated to "Needs Resubmission" - Response due by {new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toLocaleDateString()}.
          </AlertDescription>
        </Alert>
      )}

      <div className="grid gap-6 md:grid-cols-3">
        {/* Left: Submission Info */}
        <div className="md:col-span-1 space-y-4">
          <Card className="border-border bg-card">
            <CardHeader>
              <CardTitle className="text-base">Submission Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div>
                <p className="text-xs font-medium text-muted-foreground mb-1">Entity</p>
                <p className="text-sm font-semibold text-foreground">{submission.entityName}</p>
              </div>
              <div>
                <p className="text-xs font-medium text-muted-foreground mb-1">Period</p>
                <p className="text-sm font-semibold text-foreground">{submission.period}</p>
              </div>
              <div>
                <p className="text-xs font-medium text-muted-foreground mb-1">Uploaded</p>
                <p className="text-sm font-semibold text-foreground">
                  {submission.uploadedAt.toLocaleDateString()}
                </p>
              </div>
              <div>
                <p className="text-xs font-medium text-muted-foreground mb-1">Status</p>
                <Badge variant="outline" className="bg-blue-900/20 text-blue-400 border-blue-500/30">
                  {submission.status.replace('-', ' ').toUpperCase()}
                </Badge>
              </div>
            </CardContent>
          </Card>

          <Card className="border-border bg-card">
            <CardHeader>
              <CardTitle className="text-base">Calculated Metrics</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div>
                <p className="text-xs font-medium text-muted-foreground mb-1">GEI</p>
                <p className="text-2xl font-bold text-foreground">{submission.calculatedMetrics.gei}</p>
                <p className="text-xs text-muted-foreground">kg CO2e/tonne</p>
              </div>
              <div>
                <p className="text-xs font-medium text-muted-foreground mb-1">Carbon Credits</p>
                <p className="text-2xl font-bold text-emerald-400">
                  {submission.calculatedMetrics.carbonCredits.toLocaleString()}
                </p>
              </div>
              <div>
                <p className="text-xs font-medium text-muted-foreground mb-1">Data Quality</p>
                <div className="flex items-center gap-2">
                  <div className="flex-1 bg-slate-700 rounded-full h-2">
                    <div
                      className="bg-blue-500 h-2 rounded-full"
                      style={{ width: `${submission.calculatedMetrics.dataQuality}%` }}
                    />
                  </div>
                  <span className="text-sm font-semibold text-foreground">
                    {submission.calculatedMetrics.dataQuality}%
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="border-border bg-card">
            <CardHeader>
              <CardTitle className="text-base">Activity Data</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {submission.activityData.map((data: any, idx: number) => (
                <div key={idx} className="border-b border-border/30 pb-2 last:border-0 last:pb-0">
                  <p className="text-xs font-medium text-muted-foreground">{data.fuelType}</p>
                  <p className="text-sm font-semibold text-foreground">
                    {data.quantity} {data.unit}
                  </p>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>

        {/* Right: Review Section */}
        <div className="md:col-span-2">
          {!showEditor ? (
            <Card className="border-border bg-card h-full">
              <CardHeader>
                <CardTitle>Review Comments</CardTitle>
                <CardDescription>Auto-generated validation comments ready for review</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <Alert className="border-amber-500/30 bg-amber-900/20">
                  <AlertTriangle className="w-4 h-4 text-amber-400" />
                  <AlertDescription className="text-amber-300">
                    {mockAutoGeneratedComments.length} auto-generated comments found. Review, edit, and send to submitter.
                  </AlertDescription>
                </Alert>

                <div className="space-y-2">
                  {mockAutoGeneratedComments.map(comment => (
                    <div
                      key={comment.id}
                      className="border border-border rounded-lg p-3 hover:bg-muted/30 transition-colors"
                    >
                      <div className="flex items-start gap-2 mb-2">
                        <Badge
                          variant="outline"
                          className={
                            comment.severity === 'critical'
                              ? 'bg-red-900/20 text-red-400 border-red-500/30'
                              : 'bg-amber-900/20 text-amber-400 border-amber-500/30'
                          }
                        >
                          {comment.severity.toUpperCase()}
                        </Badge>
                        <Badge variant="outline" className="bg-purple-900/20 text-purple-400 border-purple-500/30">
                          Auto
                        </Badge>
                      </div>
                      <p className="text-xs text-muted-foreground mb-2">
                        Field: <span className="font-medium text-foreground">{comment.relatedField}</span>
                      </p>
                      <p className="text-sm text-foreground">{comment.commentText}</p>
                    </div>
                  ))}
                </div>

                <Button
                  onClick={() => setShowEditor(true)}
                  className="w-full gap-2 bg-blue-600 hover:bg-blue-700"
                >
                  <CheckCircle2 className="w-4 h-4" />
                  Review & Send Comments
                </Button>
              </CardContent>
            </Card>
          ) : (
            <AcvaReviewEditor
              autoComments={mockAutoGeneratedComments}
              submissionId={submissionId}
              onCancel={() => setShowEditor(false)}
              onSave={handleSendReview}
            />
          )}
        </div>
      </div>
    </div>
  )
}
