'use client'

import React, { useState } from 'react'
import { ReviewComment, ReviewCommentSeverity } from '@/lib/review-comments-schema'
import { Button } from '@/components/ui/button'
import { X, Plus, Edit2, Trash2, Send } from 'lucide-react'

interface AcvaReviewEditorProps {
  autoComments: ReviewComment[]
  submissionId: string
  onCancel: () => void
  onSave: (comments: ReviewComment[]) => void
}

export function AcvaReviewEditor({
  autoComments,
  submissionId,
  onCancel,
  onSave,
}: AcvaReviewEditorProps) {
  const [comments, setComments] = useState<ReviewComment[]>(autoComments)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editText, setEditText] = useState('')
  const [addingNew, setAddingNew] = useState(false)
  const [newCommentText, setNewCommentText] = useState('')
  const [newCommentSeverity, setNewCommentSeverity] = useState<ReviewCommentSeverity>('MAJOR')
  const [newCommentField, setNewCommentField] = useState('general')

  const handleEditComment = (comment: ReviewComment) => {
    setEditingId(comment.id)
    setEditText(comment.commentText)
  }

  const handleSaveEdit = (commentId: string) => {
    setComments(
      comments.map((c) =>
        c.id === commentId
          ? {
              ...c,
              commentText: editText,
              modifiedByReviewer: true,
              modificationHistory: [
                ...(c.modificationHistory || []),
                {
                  modifiedAt: new Date(),
                  modifiedBy: 'Dr. Priya Sharma',
                  previousText: c.commentText,
                  newText: editText,
                },
              ],
            }
          : c
      )
    )
    setEditingId(null)
    setEditText('')
  }

  const handleDeleteComment = (commentId: string) => {
    setComments(comments.filter((c) => c.id !== commentId))
  }

  const handleAddNewComment = () => {
    if (!newCommentText.trim()) return

    const newComment: ReviewComment = {
      id: `RVC-${Date.now()}`,
      submissionId,
      reviewerRole: 'acva-verifier',
      reviewerName: 'Dr. Priya Sharma',
      reviewerOrganization: 'TUV-SUD India',
      commentType: 'CAR',
      severity: newCommentSeverity,
      commentText: newCommentText,
      relatedField: newCommentField,
      createdAt: new Date(),
      resolutionStatus: 'OPEN',
      actionRequired: true,
      daysSinceCreated: 0,
      isAutoGenerated: false,
      modifiedByReviewer: false,
    }

    setComments([...comments, newComment])
    setNewCommentText('')
    setNewCommentSeverity('MAJOR')
    setNewCommentField('general')
    setAddingNew(false)
  }

  const criticalCount = comments.filter((c) => c.severity === 'CRITICAL').length
  const majorCount = comments.filter((c) => c.severity === 'MAJOR').length
  const minorCount = comments.filter((c) => c.severity === 'MINOR').length

  return (
    <div className="space-y-6 rounded-lg border border-border bg-card p-6">
      {/* Summary Stats */}
      <div className="grid grid-cols-3 gap-4 pb-6 border-b border-border">
        <div className="text-center">
          <p className="text-2xl font-bold text-red-400">{criticalCount}</p>
          <p className="text-xs text-muted-foreground">Critical</p>
        </div>
        <div className="text-center">
          <p className="text-2xl font-bold text-amber-400">{majorCount}</p>
          <p className="text-xs text-muted-foreground">Major</p>
        </div>
        <div className="text-center">
          <p className="text-2xl font-bold text-yellow-400">{minorCount}</p>
          <p className="text-xs text-muted-foreground">Minor</p>
        </div>
      </div>

      {/* Comments List */}
      <div className="space-y-3 max-h-96 overflow-y-auto">
        {comments.map((comment) => (
          <div
            key={comment.id}
            className={`rounded-lg border p-4 transition-all ${
              editingId === comment.id
                ? 'border-blue-500 bg-blue-500/10'
                : 'border-slate-600/30 bg-slate-700/20 hover:bg-slate-700/30'
            }`}
          >
            {editingId === comment.id ? (
              <div className="space-y-3">
                <textarea
                  value={editText}
                  onChange={(e) => setEditText(e.target.value)}
                  className="w-full min-h-24 rounded bg-slate-800 border border-slate-600 p-3 text-sm text-foreground focus:border-blue-500 focus:outline-none"
                />
                <div className="flex gap-2">
                  <Button
                    size="sm"
                    onClick={() => handleSaveEdit(comment.id)}
                    className="bg-blue-600 hover:bg-blue-700"
                  >
                    Save Changes
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      setEditingId(null)
                      setEditText('')
                    }}
                  >
                    Cancel
                  </Button>
                </div>
              </div>
            ) : (
              <>
                <div className="flex items-start justify-between mb-3">
                  <div className="space-y-1 flex-1">
                    <div className="flex items-center gap-2">
                      <span
                        className={`px-2 py-1 rounded text-xs font-bold ${
                          comment.severity === 'CRITICAL'
                            ? 'bg-red-500/20 text-red-300'
                            : comment.severity === 'MAJOR'
                              ? 'bg-amber-500/20 text-amber-300'
                              : 'bg-yellow-500/20 text-yellow-300'
                        }`}
                      >
                        {comment.severity}
                      </span>
                      {comment.isAutoGenerated && (
                        <span className="text-xs bg-slate-600/50 text-slate-300 px-2 py-1 rounded">
                          Auto-Generated
                        </span>
                      )}
                      {comment.modifiedByReviewer && (
                        <span className="text-xs bg-blue-600/50 text-blue-300 px-2 py-1 rounded">
                          Modified
                        </span>
                      )}
                    </div>
                    <p className="text-xs text-slate-400 mt-1">Field: {comment.relatedField}</p>
                  </div>
                </div>

                <p className="text-sm text-foreground mb-3 leading-relaxed">{comment.commentText}</p>

                <div className="flex gap-2">
                  <button
                    onClick={() => handleEditComment(comment)}
                    className="flex items-center gap-1 text-xs text-blue-400 hover:text-blue-300 transition-colors"
                  >
                    <Edit2 className="w-3 h-3" />
                    Edit
                  </button>
                  <button
                    onClick={() => handleDeleteComment(comment.id)}
                    className="flex items-center gap-1 text-xs text-red-400 hover:text-red-300 transition-colors"
                  >
                    <Trash2 className="w-3 h-3" />
                    Delete
                  </button>
                </div>
              </>
            )}
          </div>
        ))}
      </div>

      {/* Add New Comment Section */}
      {!addingNew && (
        <button
          onClick={() => setAddingNew(true)}
          className="w-full flex items-center justify-center gap-2 py-2 text-sm text-blue-400 hover:text-blue-300 transition-colors border border-dashed border-slate-600 rounded hover:border-blue-500"
        >
          <Plus className="w-4 h-4" />
          Add New Comment
        </button>
      )}

      {addingNew && (
        <div className="rounded-lg border border-blue-500/30 bg-blue-500/10 p-4 space-y-3">
          <div>
            <label className="text-sm font-semibold text-foreground mb-2 block">Comment</label>
            <textarea
              value={newCommentText}
              onChange={(e) => setNewCommentText(e.target.value)}
              placeholder="Enter your review comment..."
              className="w-full min-h-20 rounded bg-slate-800 border border-slate-600 p-3 text-sm text-foreground placeholder-slate-500 focus:border-blue-500 focus:outline-none"
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-sm font-semibold text-foreground mb-2 block">Severity</label>
              <select
                value={newCommentSeverity}
                onChange={(e) => setNewCommentSeverity(e.target.value as ReviewCommentSeverity)}
                className="w-full rounded bg-slate-800 border border-slate-600 p-2 text-sm text-foreground focus:border-blue-500 focus:outline-none"
              >
                <option value="CRITICAL">Critical</option>
                <option value="MAJOR">Major</option>
                <option value="MINOR">Minor</option>
              </select>
            </div>
            <div>
              <label className="text-sm font-semibold text-foreground mb-2 block">Field</label>
              <select
                value={newCommentField}
                onChange={(e) => setNewCommentField(e.target.value)}
                className="w-full rounded bg-slate-800 border border-slate-600 p-2 text-sm text-foreground focus:border-blue-500 focus:outline-none"
              >
                <option value="general">General</option>
                <option value="data_quality">Data Quality</option>
                <option value="gei_calculation">GEI Calculation</option>
                <option value="evidence">Evidence & Documentation</option>
                <option value="fuel_data">Fuel Data</option>
              </select>
            </div>
          </div>

          <div className="flex gap-2 pt-2">
            <Button
              size="sm"
              onClick={handleAddNewComment}
              className="bg-blue-600 hover:bg-blue-700"
            >
              Add Comment
            </Button>
            <Button
              size="sm"
              variant="outline"
              onClick={() => {
                setAddingNew(false)
                setNewCommentText('')
              }}
            >
              Cancel
            </Button>
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex gap-3 pt-6 border-t border-border">
        <Button onClick={onCancel} variant="outline">
          <X className="w-4 h-4 mr-2" />
          Cancel
        </Button>
        <Button
          onClick={() => onSave(comments)}
          className="flex-1 bg-green-600 hover:bg-green-700"
        >
          <Send className="w-4 h-4 mr-2" />
          Send Review Comments to Submitter
        </Button>
      </div>
    </div>
  )
}
