'use client'

import React, { useState } from 'react'
import { ReviewComment } from '@/lib/review-comments-schema'
import { AlertCircle, CheckCircle, Trash2, Edit2, Plus, Lock } from 'lucide-react'

interface ReviewCommentsEditorProps {
  comments: ReviewComment[]
  onCommentsChange: (comments: ReviewComment[]) => void
  readOnly?: boolean
  entityName?: string
}

/**
 * Review Comments Editor Component
 * Allows reviewers to:
 * - View auto-generated comments
 * - Modify existing auto-generated comments
 * - Delete comments they don't need
 * - Add new custom comments
 */
export function ReviewCommentsEditor({
  comments,
  onCommentsChange,
  readOnly = false,
  entityName = 'Entity',
}: ReviewCommentsEditorProps) {
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editText, setEditText] = useState('')
  const [showNewCommentForm, setShowNewCommentForm] = useState(false)
  const [newCommentText, setNewCommentText] = useState('')
  const [newCommentField, setNewCommentField] = useState('')
  const [newCommentSeverity, setNewCommentSeverity] = useState('MAJOR')

  const autoGeneratedCount = comments.filter(c => c.isAutoGenerated).length
  const customCommentCount = comments.filter(c => !c.isAutoGenerated).length

  const handleEditStart = (comment: ReviewComment) => {
    setEditingId(comment.id)
    setEditText(comment.commentText)
  }

  const handleEditSave = (commentId: string) => {
    const updatedComments = comments.map(c => {
      if (c.id === commentId) {
        return {
          ...c,
          commentText: editText,
          modifiedByReviewer: c.isAutoGenerated ? true : c.modifiedByReviewer,
          modificationHistory: [
            ...(c.modificationHistory || []),
            {
              modifiedAt: new Date(),
              modifiedBy: 'Reviewer',
              previousText: c.commentText,
              newText: editText,
            },
          ],
        }
      }
      return c
    })
    onCommentsChange(updatedComments)
    setEditingId(null)
    setEditText('')
  }

  const handleDeleteComment = (commentId: string) => {
    const updatedComments = comments.filter(c => c.id !== commentId)
    onCommentsChange(updatedComments)
  }

  const handleAddComment = () => {
    if (!newCommentText.trim()) return

    const newComment: ReviewComment = {
      id: `CUSTOM-${Date.now()}`,
      submissionId: comments[0]?.submissionId || 'unknown',
      reviewerRole: 'acva-verifier',
      reviewerName: 'Reviewer', // Would be populated from context
      reviewerOrganization: 'TUV-SUD India',
      commentType: 'QUERY',
      severity: newCommentSeverity as any,
      commentText: newCommentText,
      relatedField: newCommentField,
      createdAt: new Date(),
      resolutionStatus: 'OPEN',
      actionRequired: true,
      daysSinceCreated: 0,
      isAutoGenerated: false,
      modifiedByReviewer: false,
    }

    onCommentsChange([...comments, newComment])
    setNewCommentText('')
    setNewCommentField('')
    setNewCommentSeverity('MAJOR')
    setShowNewCommentForm(false)
  }

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'CRITICAL':
        return 'bg-red-100 text-red-700 border-red-300'
      case 'MAJOR':
        return 'bg-amber-100 text-amber-700 border-amber-300'
      case 'MINOR':
        return 'bg-yellow-100 text-yellow-700 border-yellow-300'
      default:
        return 'bg-gray-100 text-gray-700 border-gray-300'
    }
  }

  const getSeverityIcon = (severity: string) => {
    if (severity === 'CRITICAL' || severity === 'MAJOR') {
      return <AlertCircle size={16} />
    }
    return <CheckCircle size={16} />
  }

  return (
    <div className="space-y-6">
      {/* Header with counts */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold text-foreground">Review Comments</h3>
          <p className="text-xs text-muted-foreground mt-1">
            {autoGeneratedCount} auto-generated • {customCommentCount} custom • Total: {comments.length}
          </p>
        </div>
        {!readOnly && (
          <button
            onClick={() => setShowNewCommentForm(!showNewCommentForm)}
            className="flex items-center gap-2 px-3 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 text-sm font-medium"
          >
            <Plus size={16} /> Add Comment
          </button>
        )}
      </div>

      {/* Add new comment form */}
      {!readOnly && showNewCommentForm && (
        <div className="border-2 border-dashed border-primary/30 rounded-lg p-4 bg-primary/5">
          <label className="block text-sm font-medium text-foreground mb-2">Comment Text</label>
          <textarea
            value={newCommentText}
            onChange={e => setNewCommentText(e.target.value)}
            placeholder="Enter your review comment..."
            className="w-full px-3 py-2 border border-input rounded-lg bg-background text-foreground placeholder-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary mb-3 text-sm"
            rows={4}
          />
          <div className="grid grid-cols-2 gap-3 mb-3">
            <div>
              <label className="block text-sm font-medium text-foreground mb-1">Related Field</label>
              <input
                type="text"
                value={newCommentField}
                onChange={e => setNewCommentField(e.target.value)}
                placeholder="e.g., GEI, fuel_consumption"
                className="w-full px-3 py-2 border border-input rounded-lg bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-primary"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-foreground mb-1">Severity</label>
              <select
                value={newCommentSeverity}
                onChange={e => setNewCommentSeverity(e.target.value)}
                className="w-full px-3 py-2 border border-input rounded-lg bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-primary"
              >
                <option value="MINOR">MINOR</option>
                <option value="MAJOR">MAJOR</option>
                <option value="CRITICAL">CRITICAL</option>
              </select>
            </div>
          </div>
          <div className="flex gap-2">
            <button
              onClick={handleAddComment}
              className="px-3 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 text-sm font-medium"
            >
              Add Comment
            </button>
            <button
              onClick={() => setShowNewCommentForm(false)}
              className="px-3 py-2 border border-input rounded-lg hover:bg-muted text-sm font-medium text-foreground"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Comments list */}
      <div className="space-y-3">
        {comments.length === 0 ? (
          <div className="text-center py-8 bg-muted rounded-lg">
            <p className="text-sm text-muted-foreground">No review comments yet</p>
          </div>
        ) : (
          comments.map(comment => (
            <div
              key={comment.id}
              className="border border-border rounded-lg p-4 bg-card hover:shadow-sm transition-shadow"
            >
              {/* Comment header */}
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-start gap-3 flex-1">
                  <div className={`flex-shrink-0 p-2 rounded border ${getSeverityColor(comment.severity)}`}>
                    {getSeverityIcon(comment.severity)}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-sm font-semibold text-foreground">{comment.relatedField}</span>
                      <span className={`text-xs font-bold px-2 py-0.5 rounded border ${getSeverityColor(comment.severity)}`}>
                        {comment.severity}
                      </span>
                      {comment.isAutoGenerated && (
                        <span className="text-xs px-2 py-0.5 rounded bg-blue-100 text-blue-700 border border-blue-300 font-medium">
                          Auto-Generated
                        </span>
                      )}
                      {comment.modifiedByReviewer && (
                        <span className="text-xs px-2 py-0.5 rounded bg-purple-100 text-purple-700 border border-purple-300 font-medium">
                          Modified by Reviewer
                        </span>
                      )}
                    </div>
                    <p className="text-xs text-muted-foreground">
                      {comment.reviewerName} • {comment.createdAt.toLocaleDateString()}
                    </p>
                  </div>
                </div>

                {/* Action buttons */}
                {!readOnly && (
                  <div className="flex gap-2 flex-shrink-0 ml-3">
                    <button
                      onClick={() => handleEditStart(comment)}
                      className="p-2 hover:bg-muted rounded transition-colors text-muted-foreground hover:text-foreground"
                      title="Edit comment"
                    >
                      <Edit2 size={16} />
                    </button>
                    <button
                      onClick={() => handleDeleteComment(comment.id)}
                      className="p-2 hover:bg-muted rounded transition-colors text-muted-foreground hover:text-red-600"
                      title="Delete comment"
                    >
                      <Trash2 size={16} />
                    </button>
                  </div>
                )}
              </div>

              {/* Comment text - editable or display */}
              {editingId === comment.id ? (
                <div className="space-y-2">
                  <textarea
                    value={editText}
                    onChange={e => setEditText(e.target.value)}
                    className="w-full px-3 py-2 border border-input rounded-lg bg-background text-foreground placeholder-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary text-sm"
                    rows={4}
                  />
                  <div className="flex gap-2">
                    <button
                      onClick={() => handleEditSave(comment.id)}
                      className="px-3 py-1 bg-primary text-primary-foreground rounded text-sm font-medium hover:bg-primary/90"
                    >
                      Save
                    </button>
                    <button
                      onClick={() => setEditingId(null)}
                      className="px-3 py-1 border border-input rounded text-sm font-medium hover:bg-muted"
                    >
                      Cancel
                    </button>
                  </div>
                </div>
              ) : (
                <p className="text-sm text-foreground leading-relaxed mb-2">{comment.commentText}</p>
              )}

              {/* Modification history (if exists) */}
              {comment.modificationHistory && comment.modificationHistory.length > 0 && (
                <div className="mt-3 pt-3 border-t border-border">
                  <p className="text-xs font-medium text-muted-foreground mb-2">Modification History:</p>
                  <ul className="space-y-1 text-xs text-muted-foreground">
                    {comment.modificationHistory.map((mod, idx) => (
                      <li key={idx}>
                        • Modified on {mod.modifiedAt.toLocaleDateString()} by {mod.modifiedBy}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Action required indicator */}
              {comment.actionRequired && (
                <div className="mt-3 pt-3 border-t border-border flex items-center gap-2">
                  <AlertCircle size={14} className="text-amber-600" />
                  <span className="text-xs font-medium text-amber-600">Action Required from Entity</span>
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  )
}
