'use client'

import React from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription } from '@/components/ui/alert'
import {
  CheckCircle2,
  Circle,
  Clock,
  AlertCircle,
  User,
  MessageSquare,
  Zap,
  CheckCircle,
  Settings,
} from 'lucide-react'

interface WorkflowStage {
  id: string
  name: string
  actor: string
  status: 'completed' | 'current' | 'pending'
  startDate: Date | null
  endDate: Date | null
  daysRemaining: number | null
  daysSpent: number | null
  reviewCount: number
  autoGeneratedCount: number
  hasComments: boolean
}

interface SubmissionStatusTrackerProps {
  submissionId: string
  entityName: string
  currentStage: string
  stages: WorkflowStage[]
  overallProgress: number
  nextDeadline: Date | null
}

export function SubmissionStatusTracker({
  submissionId,
  entityName,
  currentStage,
  stages,
  overallProgress,
  nextDeadline,
}: SubmissionStatusTrackerProps) {
  const getStageIcon = (status: string) => {
    if (status === 'completed') return <CheckCircle2 className="w-5 h-5 text-emerald-400" />
    if (status === 'current') return <Zap className="w-5 h-5 text-amber-400" />
    return <Circle className="w-5 h-5 text-muted-foreground" />
  }

  const getStageColor = (status: string) => {
    if (status === 'completed') return 'border-emerald-500/50 bg-emerald-900/10'
    if (status === 'current') return 'border-amber-500/50 bg-amber-900/10'
    return 'border-border/50 bg-muted/30'
  }

  const currentStageData = stages.find(s => s.status === 'current')
  const completedStages = stages.filter(s => s.status === 'completed')

  return (
    <div className="space-y-4">
      {/* Current Status Alert */}
      {currentStageData && (
        <Alert className="border-amber-500/50 bg-amber-900/20">
          <AlertCircle className="w-4 h-4 text-amber-400" />
          <AlertDescription className="text-amber-300">
            <span className="font-semibold">Current Status:</span> Your submission is currently{' '}
            <span className="font-semibold">{currentStageData.name}</span> with{' '}
            <span className="font-semibold">{currentStageData.actor}</span>
            {nextDeadline && (
              <>
                {' '}
                - Response due by{' '}
                <span className="font-semibold">{nextDeadline.toLocaleDateString()}</span> (
                {currentStageData.daysRemaining} days remaining)
              </>
            )}
          </AlertDescription>
        </Alert>
      )}

      {/* Overall Progress */}
      <Card className="border-border bg-card">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-base">Submission Progress</CardTitle>
              <CardDescription>End-to-end workflow status</CardDescription>
            </div>
            <Badge variant="outline" className="text-base font-semibold">
              {overallProgress}%
            </Badge>
          </div>
        </CardHeader>
        <CardContent>
          <div className="relative h-2 bg-muted rounded-full overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-blue-500 via-purple-500 to-emerald-500 transition-all duration-500"
              style={{ width: `${overallProgress}%` }}
            />
          </div>
          <div className="mt-2 flex justify-between text-xs text-muted-foreground">
            <span>Submission Start</span>
            <span>CCC Issuance</span>
          </div>
        </CardContent>
      </Card>

      {/* Workflow Timeline */}
      <Card className="border-border bg-card">
        <CardHeader>
          <CardTitle className="text-base">Workflow Timeline</CardTitle>
          <CardDescription>Complete journey of your submission through verification</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-0">
            {stages.map((stage, index) => (
              <div key={stage.id}>
                <div className={`p-4 border rounded-lg ${getStageColor(stage.status)} transition-colors`}>
                  <div className="flex items-start gap-4">
                    {/* Stage Icon and Number */}
                    <div className="flex flex-col items-center pt-1">
                      <div className="flex items-center justify-center w-8 h-8 rounded-full border-2 border-border bg-background">
                        {getStageIcon(stage.status)}
                      </div>
                      {index < stages.length - 1 && (
                        <div className="w-0.5 h-12 bg-border/50 my-2" />
                      )}
                    </div>

                    {/* Stage Details */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-2">
                        <h4 className="font-semibold text-foreground">{stage.name}</h4>
                        <Badge
                          variant={
                            stage.status === 'completed'
                              ? 'default'
                              : stage.status === 'current'
                                ? 'outline'
                                : 'secondary'
                          }
                          className={
                            stage.status === 'completed'
                              ? 'bg-emerald-600/30 text-emerald-200'
                              : stage.status === 'current'
                                ? 'bg-amber-600/30 text-amber-200 border-amber-500/50'
                                : ''
                          }
                        >
                          {stage.status === 'completed' && '✓ Complete'}
                          {stage.status === 'current' && '• In Progress'}
                          {stage.status === 'pending' && '○ Pending'}
                        </Badge>
                      </div>

                      {/* Actor Info */}
                      <div className="flex items-center gap-2 mb-2 text-sm text-muted-foreground">
                        <User className="w-4 h-4" />
                        <span>Assigned to: {stage.actor}</span>
                      </div>

                      {/* Timeline Info */}
                      <div className="flex items-center gap-4 text-sm mb-2">
                        {stage.startDate && (
                          <div className="flex items-center gap-1 text-muted-foreground">
                            <Clock className="w-4 h-4" />
                            <span>
                              Started: {stage.startDate.toLocaleDateString()} ({stage.daysSpent} days)
                            </span>
                          </div>
                        )}
                        {stage.status === 'current' && stage.daysRemaining !== null && (
                          <div className="flex items-center gap-1 text-amber-400 font-semibold">
                            <AlertCircle className="w-4 h-4" />
                            <span>{stage.daysRemaining} days remaining</span>
                          </div>
                        )}
                        {stage.endDate && (
                          <div className="flex items-center gap-1 text-emerald-400">
                            <CheckCircle className="w-4 h-4" />
                            <span>Completed: {stage.endDate.toLocaleDateString()}</span>
                          </div>
                        )}
                      </div>

                      {/* Review Comments Info */}
                      {stage.hasComments && (
                        <div className="mt-3 pt-3 border-t border-border/50 space-y-2">
                          <div className="flex items-center gap-2 text-sm">
                            <MessageSquare className="w-4 h-4 text-blue-400" />
                            <span className="font-medium text-foreground">
                              {stage.reviewCount} Review Comment{stage.reviewCount !== 1 ? 's' : ''}
                            </span>
                          </div>
                          <div className="text-xs text-muted-foreground space-y-1 ml-6">
                            {stage.autoGeneratedCount > 0 && (
                              <div className="flex items-center gap-2">
                                <Zap className="w-3 h-3 text-yellow-500" />
                                <span>
                                  {stage.autoGeneratedCount} auto-generated by system
                                </span>
                              </div>
                            )}
                            {stage.reviewCount - stage.autoGeneratedCount > 0 && (
                              <div className="flex items-center gap-2">
                                <User className="w-3 h-3 text-blue-500" />
                                <span>
                                  {stage.reviewCount - stage.autoGeneratedCount} added/edited by reviewer
                                </span>
                              </div>
                            )}
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Key Information Summary */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <Card className="border-border bg-card">
          <CardContent className="pt-6">
            <div className="text-center">
              <CheckCircle2 className="w-6 h-6 text-emerald-400 mx-auto mb-2" />
              <p className="text-2xl font-bold text-foreground">{completedStages.length}</p>
              <p className="text-xs text-muted-foreground">Stages Completed</p>
            </div>
          </CardContent>
        </Card>

        <Card className="border-border bg-card">
          <CardContent className="pt-6">
            <div className="text-center">
              <Zap className="w-6 h-6 text-amber-400 mx-auto mb-2" />
              <p className="text-2xl font-bold text-foreground">1</p>
              <p className="text-xs text-muted-foreground">Current Stage</p>
            </div>
          </CardContent>
        </Card>

        <Card className="border-border bg-card">
          <CardContent className="pt-6">
            <div className="text-center">
              <MessageSquare className="w-6 h-6 text-blue-400 mx-auto mb-2" />
              <p className="text-2xl font-bold text-foreground">
                {stages.reduce((sum, s) => sum + s.reviewCount, 0)}
              </p>
              <p className="text-xs text-muted-foreground">Total Comments</p>
            </div>
          </CardContent>
        </Card>

        <Card className="border-border bg-card">
          <CardContent className="pt-6">
            <div className="text-center">
              <Clock className="w-6 h-6 text-purple-400 mx-auto mb-2" />
              <p className="text-2xl font-bold text-foreground">
                {nextDeadline ? Math.max(0, Math.ceil((nextDeadline.getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))) : '-'}
              </p>
              <p className="text-xs text-muted-foreground">Days to Deadline</p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Next Actions */}
      {currentStageData && (
        <Card className="border-emerald-500/30 bg-emerald-900/10">
          <CardHeader>
            <CardTitle className="text-base text-emerald-300">What's Next</CardTitle>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            <div className="space-y-2">
              <p>
                <span className="font-semibold text-foreground">Current Action:</span> Your submission is
                being reviewed by <span className="font-semibold">{currentStageData.actor}</span>. Review
                comments and feedback will appear in your dashboard.
              </p>
              <p>
                <span className="font-semibold text-foreground">You Need To:</span> Monitor for review
                comments. Once received, you'll have until{' '}
                <span className="font-semibold">
                  {nextDeadline?.toLocaleDateString()}
                </span>{' '}
                to respond with corrections or clarifications.
              </p>
              <p className="text-xs text-muted-foreground mt-3">
                💡 Tip: Check your email for notifications when new comments are added to your submission.
              </p>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
