/**
 * Review Comments Schema
 * Defines structure for verifier comments, CARs, and queries
 */

import { ReviewCommentSeverity, ReviewCommentStatus } from './dmrv-data-mapping'

export interface ReviewComment {
  id: string
  submissionId: string
  reviewerRole: 'acva-verifier' | 'check-verifier' | 'bee-officer'
  reviewerName: string
  reviewerOrganization: string
  commentType: 'CRITICAL' | 'MAJOR' | 'MINOR' | 'QUERY' | 'CAR'
  severity: ReviewCommentSeverity
  commentText: string
  relatedField: string // e.g., 'GEI', 'coal_consumption', 'calibration_cert'
  createdAt: Date
  resolvedAt?: Date
  entityResponse?: string
  entityResponseDate?: Date
  resolutionStatus: ReviewCommentStatus
  linkedDocuments?: string[]
  actionRequired: boolean
  daysSinceCreated: number
  isAutoGenerated: boolean // True if from ML/rule-based validation
  modifiedByReviewer: boolean // True if reviewer edited auto-generated comment
  modificationHistory?: {
    modifiedAt: Date
    modifiedBy: string
    previousText: string
    newText: string
  }[]
  reviewerCanModify?: boolean // Allow reviewer to edit/delete during review phase
}

/**
 * Auto-Generated Review Comment Templates
 * Covers all aspects of DMRV validation scope
 */
export interface AutoGeneratedCommentTemplate {
  id: string
  category: string
  severity: ReviewCommentSeverity
  domain: string // cement, steel, power, etc.
  template: string
  relatedField: string
  requiresDocumentation: boolean
  actionItems?: string[]
}

/**
 * Mock Review Comments for Testing
 * Shows realistic comment flow with entity responses
 */

export const MOCK_REVIEW_COMMENTS: ReviewComment[] = [
  {
    id: 'RC-001',
    submissionId: 'ECW-2024-Q1',
    reviewerRole: 'acva-verifier',
    reviewerName: 'Dr. Priya Sharma',
    reviewerOrganization: 'TUV-SUD India',
    commentType: 'CAR',
    severity: ReviewCommentSeverity.MAJOR,
    commentText:
      'Coal consumption spike of 22% observed on Jan 15-20 compared to historical baseline. Please provide explanation and supporting documentation (kiln maintenance logs, extended operation schedules, etc.) to justify the variance.',
    relatedField: 'coal_consumption',
    createdAt: new Date('2024-03-10'),
    resolvedAt: new Date('2024-03-25'),
    entityResponse:
      'During this period, kiln maintenance was extended due to emergency repairs. Supporting documentation includes maintenance logs (attached), extended shift schedules, and meter data verification from our sub-metering system.',
    entityResponseDate: new Date('2024-03-18'),
    resolutionStatus: ReviewCommentStatus.RESOLVED,
    linkedDocuments: ['kiln-maintenance-log-2024.pdf', 'shift-schedule-jan-2024.xlsx'],
    actionRequired: false,
    daysSinceCreated: 25,
  },
  {
    id: 'RC-002',
    submissionId: 'ECW-2024-Q1',
    reviewerRole: 'acva-verifier',
    reviewerName: 'Dr. Priya Sharma',
    reviewerOrganization: 'TUV-SUD India',
    commentType: 'QUERY',
    severity: ReviewCommentSeverity.MINOR,
    commentText:
      'Electricity meter calibration certificate expires on 2024-06-30. Recommend renewal before Q2 submission to ensure continued data credibility and compliance with metering standards.',
    relatedField: 'meter_calibration',
    createdAt: new Date('2024-03-15'),
    resolvedAt: undefined,
    entityResponse: undefined,
    resolutionStatus: ReviewCommentStatus.OPEN,
    actionRequired: true,
    daysSinceCreated: 20,
  },
  {
    id: 'RC-003',
    submissionId: 'ECW-2024-Q1',
    reviewerRole: 'check-verifier',
    reviewerName: 'Rajesh Kumar',
    reviewerOrganization: 'Bureau Veritas India',
    commentType: 'QUERY',
    severity: ReviewCommentSeverity.MINOR,
    commentText:
      'ACVA CAR regarding consumption spike has been adequately resolved. Kiln maintenance documentation verifies the exceptional condition. ICAP Principle 2 (Consistency) confirmed.',
    relatedField: 'verification_consistency',
    createdAt: new Date('2024-03-28'),
    resolvedAt: new Date('2024-03-29'),
    entityResponse: undefined,
    resolutionStatus: ReviewCommentStatus.RESOLVED,
    actionRequired: false,
    daysSinceCreated: 7,
  },
]

/**
 * Mock Review Comments for Resubmission Scenario
 * Example: Entity received multiple comments and needs to fix
 */

export const MOCK_PENDING_COMMENTS: ReviewComment[] = [
  {
    id: 'RC-004',
    submissionId: 'GSM-2024-Q1',
    reviewerRole: 'acva-verifier',
    reviewerName: 'Dr. Priya Sharma',
    reviewerOrganization: 'TUV-SUD India',
    commentType: 'CAR',
    severity: ReviewCommentSeverity.MAJOR,
    commentText:
      'GEI calculation shows confidence score 76%, below acceptable threshold of 85%. Missing documentation for renewable energy off-take agreement. Please provide signed agreement or MOU.',
    relatedField: 'renewable_energy_calculation',
    createdAt: new Date('2024-03-25'),
    resolvedAt: undefined,
    entityResponse: undefined,
    resolutionStatus: ReviewCommentStatus.OPEN,
    actionRequired: true,
    daysSinceCreated: 11,
  },
  {
    id: 'RC-005',
    submissionId: 'GSM-2024-Q1',
    reviewerRole: 'acva-verifier',
    reviewerName: 'Dr. Priya Sharma',
    reviewerOrganization: 'TUV-SUD India',
    commentType: 'QUERY',
    severity: ReviewCommentSeverity.MAJOR,
    commentText:
      'Activity data completeness: Missing monthly breakdown for March 2024. Only summary provided. Please submit detailed monthly activity data with daily readings for complete quarter coverage.',
    relatedField: 'activity_data_completeness',
    createdAt: new Date('2024-03-26'),
    resolvedAt: undefined,
    entityResponse: undefined,
    resolutionStatus: ReviewCommentStatus.OPEN,
    actionRequired: true,
    daysSinceCreated: 10,
  },
  {
    id: 'RC-006',
    submissionId: 'GSM-2024-Q1',
    reviewerRole: 'acva-verifier',
    reviewerName: 'Dr. Priya Sharma',
    reviewerOrganization: 'TUV-SUD India',
    commentType: 'MINOR',
    severity: ReviewCommentSeverity.MINOR,
    commentText:
      'Evidence pack organization: Please provide table of contents for evidence attachments. Current submission has 47 files without clear indexing. This helps verification traceability.',
    relatedField: 'evidence_documentation',
    createdAt: new Date('2024-03-27'),
    resolvedAt: undefined,
    entityResponse: undefined,
    resolutionStatus: ReviewCommentStatus.OPEN,
    actionRequired: false,
    daysSinceCreated: 9,
  },
]

/**
 * Helper function to count pending comments by severity
 */
export function countPendingComments(comments: ReviewComment[]): {
  total: number
  critical: number
  major: number
  minor: number
  actionRequired: number
} {
  const pending = comments.filter(c => c.resolutionStatus === ReviewCommentStatus.OPEN)

  return {
    total: pending.length,
    critical: pending.filter(c => c.severity === ReviewCommentSeverity.CRITICAL).length,
    major: pending.filter(c => c.severity === ReviewCommentSeverity.MAJOR).length,
    minor: pending.filter(c => c.severity === ReviewCommentSeverity.MINOR).length,
    actionRequired: pending.filter(c => c.actionRequired).length,
  }
}

/**
 * Auto-Generated Review Comment Templates by DMRV Validation Scope
 * These templates cover all validation aspects and can be customized by reviewers
 */
export const AUTO_GENERATED_COMMENT_TEMPLATES: AutoGeneratedCommentTemplate[] = [
  // CATEGORY 1: DATA SCHEMA & COMPLETENESS
  {
    id: 'AGT-001',
    category: 'Data Schema & Completeness',
    severity: ReviewCommentSeverity.CRITICAL,
    domain: 'all',
    template:
      'Schema Validation: All mandatory fields (Fuel type, Quantity, Unit, Calorific Value, Oxidation Factor) are present and correctly formatted. XML structure complies with dMRV specification v2.1. No data type mismatches detected.',
    relatedField: 'schema_validation',
    requiresDocumentation: false,
    actionItems: ['Review schema compliance', 'Validate data types'],
  },
  {
    id: 'AGT-002',
    category: 'Data Completeness',
    severity: ReviewCommentSeverity.MAJOR,
    domain: 'all',
    template:
      'Completeness Check: Daily activity records are complete for the submission period (Q1 2024: Jan 1 - Mar 31). No missing days or null values detected in coal consumption, electricity generation, or production output data. Coverage: 100% (90/90 days).',
    relatedField: 'activity_data_completeness',
    requiresDocumentation: true,
    actionItems: ['Verify date range', 'Check for gaps in daily records'],
  },

  // CATEGORY 2: DATA QUALITY & CONFIDENCE SCORING
  {
    id: 'AGT-003',
    category: 'Data Quality & Confidence',
    severity: ReviewCommentSeverity.CRITICAL,
    domain: 'all',
    template:
      'Data Quality Assessment: Overall confidence score is 88%, indicating HIGH credibility. Calculation basis: Schema compliance (100%), Field completeness (100%), Evidence credibility (85%), Anomaly resolution (75%). Minimum threshold of 85% met. dMRV Quality Index: PASS.',
    relatedField: 'data_quality_score',
    requiresDocumentation: false,
    actionItems: ['Verify confidence calculation', 'Review evidence credibility factors'],
  },

  // CATEGORY 3: FUEL/ACTIVITY DATA ANOMALIES (ML DETECTED)
  {
    id: 'AGT-004',
    category: 'Fuel Data Anomalies',
    severity: ReviewCommentSeverity.MAJOR,
    domain: 'cement',
    template:
      'Anomaly Detected: Coal consumption increased 18% on Jan 15-20, 2024 (5,520 tonnes vs baseline 4,674 tonnes). ML model flags this as potential outlier. However, entity provided kiln maintenance logs explaining extended operation schedule. Anomaly JUSTIFIED. Supporting evidence: maintenance log, shift schedules, meter calibration certificate.',
    relatedField: 'fuel_consumption_anomalies',
    requiresDocumentation: true,
    actionItems: [
      'Review anomaly explanation',
      'Validate supporting documentation',
      'Confirm kiln maintenance schedule',
    ],
  },
  {
    id: 'AGT-005',
    category: 'Production Output Variance',
    severity: ReviewCommentSeverity.MAJOR,
    domain: 'cement',
    template:
      'Production Output Check: Cement produced shows 12% variance vs 3-year average (540 tonnes vs 483 tonnes monthly average). Rule-based analysis indicates this is within acceptable ±15% manufacturing variance range. GEI calculation adjusted accordingly. Status: ACCEPTABLE.',
    relatedField: 'production_output_variance',
    requiresDocumentation: true,
    actionItems: ['Verify production records', 'Check against equipment capacity'],
  },

  // CATEGORY 4: EVIDENCE & DOCUMENTATION
  {
    id: 'AGT-006',
    category: 'Evidence & Documentation',
    severity: ReviewCommentSeverity.CRITICAL,
    domain: 'all',
    template:
      'Evidence Package Review: 47 supporting documents provided. All certificates (calibration, audit, compliance) are valid and current. Coal invoices dated with supplier details. Electricity meter logs cover entire submission period. ISO/IEC 17025 accreditation verified for calibration laboratory. Evidence credibility: 85%.',
    relatedField: 'evidence_documentation',
    requiresDocumentation: false,
    actionItems: [
      'Verify certificate expiry dates',
      'Cross-check supplier invoices',
      'Validate meter calibration scope',
    ],
  },
  {
    id: 'AGT-007',
    category: 'Meter Calibration Certificate',
    severity: ReviewCommentSeverity.MAJOR,
    domain: 'all',
    template:
      'Calibration Status: Electricity meter calibration certificate is valid until 2024-06-30 (Expires in 3 months). Recommends renewal before Q2 2024 submission (deadline Aug 15) to ensure uninterrupted compliance. Current certificate: TUV-SUD ref CAL-2023-4521, Scope: 0-500A, Accuracy ±0.2%.',
    relatedField: 'meter_calibration_cert',
    requiresDocumentation: false,
    actionItems: ['Schedule calibration renewal', 'Plan renewal timing before Q2'],
  },

  // CATEGORY 5: BASELINE & GEI CONSISTENCY
  {
    id: 'AGT-008',
    category: 'Baseline Alignment',
    severity: ReviewCommentSeverity.CRITICAL,
    domain: 'all',
    template:
      'Baseline Compliance: Facility GEI (1,361.84 kg CO2e/tonne) is 10.4% below BEE baseline (1,520 kg CO2e/tonne) for cement sector 2024. Performance: OVER-PERFORMER status confirmed. CCC eligibility: YES. Over-performance benefit: 19,288 CCCs for Q1 2024.',
    relatedField: 'gei_baseline_comparison',
    requiresDocumentation: false,
    actionItems: ['Confirm baseline applicability', 'Verify GEI calculation methodology'],
  },
  {
    id: 'AGT-009',
    category: 'GEI Calculation Verification',
    severity: ReviewCommentSeverity.MAJOR,
    domain: 'all',
    template:
      'GEI Calculation: Manual verification performed using provided activity data and emission factors (coal: 25.4 kg CO2/GJ, electricity: 0.65 kg CO2/kWh). Calculated GEI: 1,361.84 kg CO2e/tonne. Matches entity submission. Deviation: 0% (Perfect match). Confidence: 96%.',
    relatedField: 'gei_calculation',
    requiresDocumentation: false,
    actionItems: ['Verify emission factor sources', 'Cross-check fuel specifications'],
  },

  // CATEGORY 6: DUPLICATE DETECTION & RECONCILIATION
  {
    id: 'AGT-010',
    category: 'Duplicate Detection',
    severity: ReviewCommentSeverity.CRITICAL,
    domain: 'all',
    template:
      'Duplicate & Double-Counting Check: No duplicate activity records detected across submission data. Reconciliation with previous quarters (2023-Q4, 2023-Q3, 2023-Q2) shows clean cutoff. No overlapping dates or amounts. Data integrity: VERIFIED.',
    relatedField: 'duplicate_detection',
    requiresDocumentation: false,
    actionItems: ['Cross-check quarterly reconciliation', 'Verify no carryover entries'],
  },

  // CATEGORY 7: METHODOLOGY COMPLIANCE & ICAP PRINCIPLES
  {
    id: 'AGT-011',
    category: 'ICAP Principles Compliance',
    severity: ReviewCommentSeverity.CRITICAL,
    domain: 'all',
    template:
      'ICAP Compliance Review: All 4 EU MRV principles verified. (1) Completeness: All data fields present. (2) Consistency: Data aligns internally and with historical trends. (3) Accuracy: Within ±5% materiality threshold. (4) Integrity: Verifier independence confirmed (no conflicts with entity). Status: COMPLIANT.',
    relatedField: 'icap_principles',
    requiresDocumentation: false,
    actionItems: [
      'Verify each ICAP principle implementation',
      'Document verifier independence declaration',
    ],
  },
  {
    id: 'AGT-012',
    category: 'Methodology Rule-Based Deviations',
    severity: ReviewCommentSeverity.MAJOR,
    domain: 'all',
    template:
      'Rule-Based Compliance: Entity follows prescribed GEI calculation methodology per CCTS guidelines. Fuel calorific values sourced from Schedule IV (Fuel specifications). Emission factors from IPCC AR5 defaults. No deviations from approved methodology. Compliance: PASS.',
    relatedField: 'methodology_compliance',
    requiresDocumentation: false,
    actionItems: ['Verify emission factor documentation', 'Confirm fuel specifications used'],
  },
]

/**
 * Function to generate auto-review comments for a submission
 * Simulates ML/rule-based validation results
 */
export function generateAutoReviewComments(submissionId: string, entityName: string): ReviewComment[] {
  const baseDate = new Date('2024-03-28')
  const reviewerName = 'Dr. Priya Sharma'
  const reviewerOrg = 'TUV-SUD India'

  // Select subset of templates as auto-generated comments (typically 5-7)
  const selectedTemplates = AUTO_GENERATED_COMMENT_TEMPLATES.slice(0, 7)

  return selectedTemplates.map((template, index) => ({
    id: `AGC-${submissionId}-${index + 1}`,
    submissionId,
    reviewerRole: 'acva-verifier' as const,
    reviewerName,
    reviewerOrganization: reviewerOrg,
    commentType: 'QUERY' as const,
    severity: template.severity,
    commentText: template.template,
    relatedField: template.relatedField,
    createdAt: new Date(baseDate.getTime() + index * 3600000), // Stagger by 1 hour
    resolutionStatus: ReviewCommentStatus.OPEN,
    actionRequired: template.requiresDocumentation,
    daysSinceCreated: 0,
    isAutoGenerated: true,
    modifiedByReviewer: false,
    reviewerCanModify: true,
  }))
}

/**
 * Helper function to format comment for display
 */
export function formatCommentDate(date: Date): string {
  return new Intl.DateTimeFormat('en-IN', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date)
}
