'use client'

import React, { useState } from 'react'
import { useRole } from '@/lib/role-context'
import { AppShell } from '@/components/app-shell'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { AlertCircle, CheckCircle2, AlertTriangle, Download, Upload, Send } from 'lucide-react'
import { mockLifecycleEvents } from '@/lib/mock-data'

// Mock feedback data from ACVA verifiers
const mockFeedbackQueue = [
  {
    id: 'FB-2024-001',
    submissionId: 'SUB-2024-Q1-ECW',
    entity: 'Eastern Cement Works',
    quarter: 'Q1 2024',
    reviewedBy: 'Dr. Priya Sharma',
    reviewDate: '2024-03-30',
    status: 'needs-response',
    severity: 'major',
    comments: [
      {
        id: 'cmt-1',
        field: 'Fuel Data - Coal Energy Source',
        severity: 'major',
        text: 'Coal consumption data shows 15% variance from historical baseline. Please provide supporting documentation or clarification.',
        autoGenerated: true,
        submitterResponse: null
      },
      {
        id: 'cmt-2',
        field: 'Production Output',
        severity: 'minor',
        text: 'Production output data for Q1 peak appears to be missing 2 data points. Please upload complete dataset.',
        autoGenerated: true,
        submitterResponse: null
      },
      {
        id: 'cmt-3',
        field: 'Baseline & GEI Consistency',
        severity: 'minor',
        text: 'GEI calculation matches baseline. Minor notation: Ensure latest emission factor version is documented.',
        autoGenerated: false,
        submitterResponse: null
      }
    ]
  }
]

export default function SubmissionFeedbackPage() {
  const { currentRole } = useRole()
  const [selectedFeedback, setSelectedFeedback] = useState<string | null>(null)
  const [responses, setResponses] = useState<Record<string, string>>({})
  const [isUploading, setIsUploading] = useState(false)

  // Only allow Obligated Entity to access this page
  if (currentRole !== 'obligated-entity') {
    return (
      <AppShell currentPage="submissions" lifecycleEvents={mockLifecycleEvents}>
        <div className="max-w-4xl mx-auto p-6">
          <div className="rounded-lg border border-red-200 bg-red-50/5 p-6 text-center">
            <AlertCircle className="w-12 h-12 text-red-400 mx-auto mb-4" />
            <p className="text-red-300">Access Denied</p>
            <p className="text-sm text-red-200 mt-2">Only Obligated Entities can view submission feedback.</p>
          </div>
        </div>
      </AppShell>
    )
  }

  const activeFeedback = mockFeedbackQueue.find(fb => fb.id === selectedFeedback)

  const handleResponseChange = (commentId: string, response: string) => {
    setResponses(prev => ({
      ...prev,
      [commentId]: response
    }))
  }

  const handleResubmit = async () => {
    setIsUploading(true)
    // Simulate upload delay
    await new Promise(resolve => setTimeout(resolve, 2000))
    setIsUploading(false)
    alert('Resubmission uploaded successfully! ACVA verifier will review your responses.')
  }

  return (
    <AppShell currentPage="submissions" lifecycleEvents={mockLifecycleEvents}>
      <div className="max-w-7xl mx-auto p-6">
        <div className="space-y-6">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold text-foreground">Review Feedback & Resubmit</h1>
            <p className="text-muted-foreground">Address ACVA verification comments and resubmit corrected data</p>
          </div>

          <div className="grid lg:grid-cols-3 gap-6">
            {/* Feedback Queue */}
            <div className="lg:col-span-1">
              <Card className="border-border">
                <CardHeader>
                  <CardTitle className="text-lg">Feedback Queue</CardTitle>
                  <CardDescription>Pending review responses</CardDescription>
                </CardHeader>
                <CardContent className="space-y-2">
                  {mockFeedbackQueue.map(feedback => (
                    <button
                      key={feedback.id}
                      onClick={() => setSelectedFeedback(feedback.id)}
                      className={`w-full text-left p-3 rounded-lg border-2 transition-all ${
                        selectedFeedback === feedback.id
                          ? 'border-blue-500 bg-blue-500/10'
                          : 'border-border hover:border-slate-500 hover:bg-slate-700/30'
                      }`}
                    >
                      <div className="flex items-start justify-between">
                        <div className="flex-1 min-w-0">
                          <p className="font-semibold text-foreground text-sm">{feedback.entity}</p>
                          <p className="text-xs text-muted-foreground">{feedback.quarter}</p>
                          <div className="flex gap-2 mt-2">
                            <span className="text-xs px-2 py-1 rounded-full bg-amber-500/20 text-amber-300">
                              {feedback.comments.filter(c => c.severity === 'major').length} Major
                            </span>
                            <span className="text-xs px-2 py-1 rounded-full bg-blue-500/20 text-blue-300">
                              {feedback.comments.filter(c => c.severity === 'minor').length} Minor
                            </span>
                          </div>
                        </div>
                      </div>
                    </button>
                  ))}
                </CardContent>
              </Card>
            </div>

            {/* Feedback Details & Response Form */}
            <div className="lg:col-span-2">
              {activeFeedback ? (
                <div className="space-y-4">
                  {/* Feedback Header */}
                  <Card className="border-border">
                    <CardHeader>
                      <div className="flex items-start justify-between">
                        <div>
                          <CardTitle>{activeFeedback.entity}</CardTitle>
                          <CardDescription className="mt-2">
                            Reviewed by {activeFeedback.reviewedBy} on {activeFeedback.reviewDate}
                          </CardDescription>
                        </div>
                        <span className="text-xs px-3 py-1 rounded-full bg-amber-500/20 text-amber-300 font-semibold">
                          NEEDS RESPONSE
                        </span>
                      </div>
                    </CardHeader>
                  </Card>

                  {/* Comments */}
                  <div className="space-y-3">
                    {activeFeedback.comments.map(comment => (
                      <Card key={comment.id} className="border-border">
                        <CardHeader className="pb-3">
                          <div className="flex items-start justify-between gap-4">
                            <div className="flex-1">
                              <div className="flex items-center gap-2 mb-2">
                                <span className="font-semibold text-foreground">{comment.field}</span>
                                <span className={`text-xs px-2 py-1 rounded-full font-semibold ${
                                  comment.severity === 'major'
                                    ? 'bg-red-500/20 text-red-300'
                                    : 'bg-blue-500/20 text-blue-300'
                                }`}>
                                  {comment.severity === 'major' ? 'MAJOR' : 'MINOR'}
                                </span>
                                {comment.autoGenerated && (
                                  <span className="text-xs px-2 py-1 rounded-full bg-slate-700/50 text-slate-300">
                                    AI-Generated
                                  </span>
                                )}
                              </div>
                              <p className="text-sm text-foreground leading-relaxed">{comment.text}</p>
                            </div>
                          </div>
                        </CardHeader>
                        <CardContent className="space-y-3 pt-0">
                          <textarea
                            placeholder="Your response or clarification..."
                            value={responses[comment.id] || ''}
                            onChange={(e) => handleResponseChange(comment.id, e.target.value)}
                            className="w-full px-3 py-2 rounded-lg bg-slate-700/30 border border-slate-600 text-foreground placeholder-muted-foreground text-sm resize-none h-24"
                          />
                          {responses[comment.id] && (
                            <div className="flex items-center gap-2 text-xs text-emerald-400">
                              <CheckCircle2 className="w-4 h-4" />
                              Response recorded
                            </div>
                          )}
                        </CardContent>
                      </Card>
                    ))}
                  </div>

                  {/* File Upload & Resubmission */}
                  <Card className="border-emerald-500/30 bg-emerald-900/10">
                    <CardHeader>
                      <CardTitle className="text-emerald-300">Upload Corrected Data</CardTitle>
                      <CardDescription>Resubmit with corrected files after addressing feedback</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <div className="border-2 border-dashed border-emerald-500/50 rounded-lg p-6 text-center">
                        <Upload className="w-8 h-8 text-emerald-400 mx-auto mb-2" />
                        <p className="text-sm text-emerald-300 mb-2">Drag and drop corrected CSV files here</p>
                        <Button className="bg-emerald-600 hover:bg-emerald-700 text-white">
                          Choose Files
                        </Button>
                      </div>

                      <div className="flex gap-2">
                        <Button
                          onClick={handleResubmit}
                          disabled={isUploading}
                          className="flex-1 bg-emerald-600 hover:bg-emerald-700"
                        >
                          <Send className="w-4 h-4 mr-2" />
                          {isUploading ? 'Resubmitting...' : 'Resubmit for Review'}
                        </Button>
                        <Button variant="outline" className="flex-1">
                          <Download className="w-4 h-4 mr-2" />
                          Download Template
                        </Button>
                      </div>

                      <div className="p-3 rounded-lg bg-slate-700/30 border border-slate-600 flex gap-3">
                        <AlertTriangle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
                        <div className="text-sm text-muted-foreground">
                          <p className="font-semibold text-foreground mb-1">Please note:</p>
                          <ul className="space-y-1 text-xs">
                            <li>• Address all major comments before resubmission</li>
                            <li>• Include clarification for any discrepancies</li>
                            <li>• Supporting documentation can be attached as evidence</li>
                            <li>• ACVA verifier will review within 5 business days</li>
                          </ul>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              ) : (
                <Card className="border-border">
                  <CardContent className="pt-12 pb-12">
                    <div className="text-center">
                      <CheckCircle2 className="w-12 h-12 text-emerald-400 mx-auto mb-4" />
                      <p className="text-foreground font-semibold mb-2">No Pending Feedback</p>
                      <p className="text-sm text-muted-foreground">Select a submission to view feedback and resubmit if needed.</p>
                    </div>
                  </CardContent>
                </Card>
              )}
            </div>
          </div>
        </div>
      </div>
    </AppShell>
  )
}
