'use client'

import React from 'react'
import { useParams } from 'next/navigation'
import { AppShell } from '@/components/app-shell'
import { SubmissionStatusTracker } from '@/components/submission-status-tracker'
import { mockLifecycleEvents } from '@/lib/mock-data'

export default function SubmissionStatusPage() {
  const params = useParams()
  const submissionId = params.id as string

  // Mock data - in production, this would come from the database
  const mockStages = [
    {
      id: 'stage-1',
      name: 'Data Upload & Validation',
      actor: 'DMRV System',
      status: 'completed' as const,
      startDate: new Date('2024-03-28'),
      endDate: new Date('2024-03-28'),
      daysRemaining: null,
      daysSpent: 0,
      reviewCount: 7,
      autoGeneratedCount: 7,
      hasComments: true,
    },
    {
      id: 'stage-2',
      name: 'ACVA Verification Review',
      actor: 'Dr. Priya Sharma (TUV-SUD)',
      status: 'current' as const,
      startDate: new Date('2024-03-29'),
      endDate: null,
      daysRemaining: 12,
      daysSpent: 8,
      reviewCount: 14,
      autoGeneratedCount: 7,
      hasComments: true,
    },
    {
      id: 'stage-3',
      name: 'Entity Response & Resubmission',
      actor: 'Eastern Cement Works',
      status: 'pending' as const,
      startDate: null,
      endDate: null,
      daysRemaining: null,
      daysSpent: null,
      reviewCount: 0,
      autoGeneratedCount: 0,
      hasComments: false,
    },
    {
      id: 'stage-4',
      name: 'Check-Verifier Independent Audit',
      actor: 'Bureau Veritas (Independent)',
      status: 'pending' as const,
      startDate: null,
      endDate: null,
      daysRemaining: null,
      daysSpent: null,
      reviewCount: 0,
      autoGeneratedCount: 0,
      hasComments: false,
    },
    {
      id: 'stage-5',
      name: 'BEE Officer Final Review & CCC Issuance',
      actor: 'BEE Approver',
      status: 'pending' as const,
      startDate: null,
      endDate: null,
      daysRemaining: null,
      daysSpent: null,
      reviewCount: 0,
      autoGeneratedCount: 0,
      hasComments: false,
    },
    {
      id: 'stage-6',
      name: 'NSCICM & Central Govt Approval',
      actor: 'National CCTS Governing Council',
      status: 'pending' as const,
      startDate: null,
      endDate: null,
      daysRemaining: null,
      daysSpent: null,
      reviewCount: 0,
      autoGeneratedCount: 0,
      hasComments: false,
    },
    {
      id: 'stage-7',
      name: 'Carbon Credits Issued & Registered',
      actor: 'ICM Registry (Blockchain)',
      status: 'pending' as const,
      startDate: null,
      endDate: null,
      daysRemaining: null,
      daysSpent: null,
      reviewCount: 0,
      autoGeneratedCount: 0,
      hasComments: false,
    },
  ]

  const nextDeadline = new Date('2024-04-10')
  const overallProgress = 25 // 1 of 7 stages completed

  return (
    <AppShell currentPage="submissions" lifecycleEvents={mockLifecycleEvents}>
      <div className="p-6 max-w-6xl mx-auto">
        <div className="space-y-6">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold text-foreground">Submission Status & Workflow</h1>
            <p className="text-muted-foreground">
              Complete journey of submission {submissionId} through the CCTS verification process
            </p>
          </div>

          <SubmissionStatusTracker
            submissionId={submissionId}
            entityName="Eastern Cement Works"
            currentStage="ACVA Verification Review"
            stages={mockStages}
            overallProgress={overallProgress}
            nextDeadline={nextDeadline}
          />
        </div>
      </div>
    </AppShell>
  )
}
